import type { Commitment, Plan, Pot } from "./types";
import { dayKey, monthRange } from "./dates";

/** The Oct 2026 → Mar 2027 plan, written on first login. Everything is editable in Settings. */
export function seedPlan(today: string = dayKey()): Plan {
  return {
    periodStart: "2026-10",
    periodEnd: "2027-03",
    openingCash: 39000,
    openingDate: today < "2026-10-01" ? "2026-10-01" : today,
    salary: {
      gross: 75000,
      officeScheme: 10000,
      toParents: 25000,
      creditDay: 1,
      // Each month's pay funds the next month, so Oct's salary lands ~Nov 1.
      months: monthRange("2026-11", "2027-03"),
    },
    incomes: [
      { id: "oct-oneoff", label: "One-time inflow", amount: 60000, date: "2026-10-15" },
      { id: "office-payout", label: "Office savings scheme payout", amount: 60000, date: "2027-03-31" },
    ],
    laptopFund: 60000,
    categories: [
      { id: "cooking", name: "Cooking", jp: "料理", emoji: "🥬", monthly: 4000, color: "green" },
      { id: "meat", name: "Meat", jp: "肉", emoji: "🍗", monthly: 2500, color: "red" },
      { id: "stay", name: "Monthly stay", jp: "宿", emoji: "🏠", monthly: 5000, tripMonthly: 0, color: "violet" },
      { id: "petrol", name: "Petrol", jp: "油", emoji: "⛽", monthly: 500, color: "yellow" },
      { id: "perfume", name: "Perfumes", jp: "香", emoji: "🧴", monthly: 1500, color: "cyan" },
      { id: "fun", name: "Fun / impulse", jp: "遊", emoji: "🎮", monthly: 0, isRemainder: true, color: "pink" },
    ],
    monthlyCap: 14000,
    tripMonthCap: 9000,
    tripMonths: ["2026-10", "2027-01"],
    savingsTargets: {
      "2026-10": 75000,
      "2026-11": 16000,
      "2026-12": 19000,
      "2027-01": 12000,
      "2027-02": 16000,
      "2027-03": 20000,
    },
    goal: 195000,
    milestones: [50000, 100000, 150000, 200000],
    installmentWarn: 5000,
    wishlistThreshold: 1000,
    wishlistHours: 48,
  };
}

type SeedCommitment = Omit<Commitment, "skipped" | "paidMonths" | "order">;

export function seedCommitments(): Commitment[] {
  const items: SeedCommitment[] = [
    {
      id: "loan",
      name: "Long-term loan",
      amount: 2600,
      months: monthRange("2026-10", "2027-03"),
      kind: "installment",
      mode: "loan",
      mustPay: true,
      optional: false,
      ongoing: true,
    },
    {
      id: "inst-2200",
      name: "2.2k installment",
      amount: 2200,
      months: ["2026-10"],
      kind: "installment",
      mode: "emi",
      mustPay: true,
      optional: false,
      note: "Nov's payment is inside the 7.1k paylater",
    },
    {
      id: "inst-800",
      name: "800 installment",
      amount: 800,
      months: ["2026-10", "2026-11"],
      kind: "installment",
      mode: "emi",
      mustPay: true,
      optional: false,
      note: "Ending soon. Set the real end month",
    },
    {
      id: "bill-1500",
      name: "Monthly bill",
      amount: 1500,
      months: ["2026-11", "2026-12"],
      kind: "installment",
      mode: "bill",
      mustPay: true,
      optional: false,
    },
    {
      id: "paylater-nov",
      name: "Paylater",
      amount: 7100,
      months: ["2026-11"],
      kind: "one-time",
      mode: "paylater",
      mustPay: true,
      optional: false,
    },
    {
      id: "laptop-emi",
      name: "Laptop EMI",
      amount: 3300,
      months: monthRange("2026-11", "2027-04"),
      kind: "installment",
      mode: "emi",
      mustPay: true,
      optional: false,
      note: "My 20k share, no-cost EMI",
    },
    {
      id: "train",
      name: "Train tickets",
      amount: 4000,
      months: ["2027-02"],
      kind: "one-time",
      mode: "paylater",
      mustPay: true,
      optional: false,
    },
    {
      id: "oct-trip",
      name: "Oct 30 trip",
      amount: 10000,
      months: ["2026-10"],
      kind: "one-time",
      mode: "cash",
      mustPay: false,
      optional: false,
    },
    {
      id: "festive",
      name: "Festive clothes",
      amount: 2500,
      months: ["2026-10"],
      kind: "one-time",
      mode: "cash",
      mustPay: false,
      optional: false,
    },
    {
      id: "course",
      name: "Course registration",
      amount: 20000,
      months: ["2027-01"],
      kind: "one-time",
      mode: "cash",
      mustPay: true,
      optional: false,
      note: "Must pay. Never skip",
    },
    {
      id: "jan-hotel",
      name: "Jan trip: hotel",
      amount: 10000,
      months: ["2027-01"],
      kind: "one-time",
      mode: "cash",
      mustPay: false,
      optional: false,
      note: "6–10k, update when booked",
    },
    {
      id: "jan-cash",
      name: "Jan trip: cash",
      amount: 5000,
      months: ["2027-01"],
      kind: "one-time",
      mode: "cash",
      mustPay: false,
      optional: false,
      note: "Food is covered",
    },
    {
      id: "watch",
      name: "Watch",
      amount: 10000,
      months: ["2027-03"],
      kind: "one-time",
      mode: "cash",
      mustPay: false,
      optional: true,
      note: "Pay outright, not on EMI",
    },
  ];
  return items.map((c, i) => ({ ...c, skipped: false, paidMonths: [], order: i }));
}

export function seedPots(): Pot[] {
  return [
    { id: "course-pot", name: "Course fee", jp: "学費", target: 20000, saved: 0, commitmentIds: ["course"], order: 0 },
    {
      id: "trip-pot",
      name: "January trip",
      jp: "旅行",
      target: 15000,
      saved: 0,
      commitmentIds: ["jan-hotel", "jan-cash"],
      order: 1,
    },
  ];
}
